# GitHub Actions workflow to test PRs before merge
# This workflow runs tests on pull requests targeting the main branch

name: Test PRs

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: Run tests
        run: uv run hatch test
